### ISSUE TITLE
Replace try-catch in tests

### ISSUE THREAD

**Issue by OwenArnold** [ANSTO-ACNS/bilby-gui#13]
You'd save yourselves loads of lines of code if you used the built in  `assertRaises` instead of the try-catch block(s) see [docs](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertRaises)

**Comment by AntonPiccardoSelg** [comment]
Python does not come with `assertRaisesNothing`. Using

```python
try:
   doSomething()
   has_raised = False
except MyException:
   has_raised = True
self.assertTrue(has_raised)
```
is a common way to test that a function does not raise anythong [see here](http://stackoverflow.com/questions/8747771/how-to-use-python-unittest-assertraises-to-test-that-function-doesnt-throws-any).

**Comment by OwenArnold** [comment]
That seems reasonable enough.
